export const FAVORITE_CATEGORIES: string[] = [
    'Animals',
    'Art',
    'Body',
    'Books',
    'Business',
    'Clothing',
    'Colors',
    'Culture',
    'Daily Routine',
    'Education',
    'Emotions',
    'Family',
    'Fashion',
    'Fitness',
    'Food',
    'Gaming',
    'Geography',
    'Health',
    'History',
    'Hobbies',
    'Holidays',
    'Home',
    'Hotels',
    'Idiomatic Expressions',
    'Idioms',
    'Marketing',
    'Medicine',
    'Money',
    'Movies',
    'Music',
    'Nature',
    'Numbers',
    'Office',
    'Phrasal Verbs',
    'Politics',
    'Programming',
    'Relationships',
    'Restaurants',
    'School',
    'Science',
    'Shopping',
    'Social Media',
    'Sports',
    'Technology',
    'Time',
    'Transportation',
    'Travel',
    'University',
    'Weather',
    'Work'
];
