export const FAVORITE_CATEGORY_CALLBACK_PREFIX = 'favorite_category:';

export const FAVORITE_CATEGORIES: string[] = [
    'Travel',
    'Food',
    'Family',
    'Work',
    'Education',
    'Health',
    'Fitness',
    'Shopping',
    'Hobbies',
    'Nature',
    'Technology',
    'Art',
    'Music',
    'Movies',
    'Books',
    'Sports',
    'Weather',
    'Transportation',
    'Home',
    'Money',
    'Fashion',
    'Animals',
    'Politics',
    'Science',
    'History',
    'Geography',
    'Business',
    'Marketing',
    'Programming',
    'Gaming',
    'Social Media',
    'Relationships',
    'Emotions',
    'Daily Routine',
    'Time',
    'Numbers',
    'Colors',
    'Clothing',
    'Body',
    'Medicine',
    'School',
    'University',
    'Office',
    'Restaurants',
    'Hotels',
    'Holidays',
    'Culture',
    'Idioms',
    'Phrasal Verbs',
    'Idiomatic Expressions'
];
